In [3]:
import pandas as pd

In [11]:
df = pd.read_csv('../datasets/iris.csv', header=None)

In [8]:
df.head()

0             1            2             3            4        5
0  NaN  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
1  1.0           5.1          3.5           1.4          0.2   setosa
2  2.0           4.9            3           1.4          0.2   setosa
3  3.0           4.7          3.2           1.3          0.2   setosa
4  4.0           4.6          3.1           1.5          0.2   setosa

In [ ]:
df.taill()

In [9]:
df = df.drop(0)

In [12]:
df.head()

0             1            2             3            4        5
0  NaN  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
1  1.0           5.1          3.5           1.4          0.2   setosa
2  2.0           4.9            3           1.4          0.2   setosa
3  3.0           4.7          3.2           1.3          0.2   setosa
4  4.0           4.6          3.1           1.5          0.2   setosa

In [13]:
df = df.drop(0, 1)

In [14]:
df.head()

1            2             3            4        5
0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
1           5.1          3.5           1.4          0.2   setosa
2           4.9            3           1.4          0.2   setosa
3           4.7          3.2           1.3          0.2   setosa
4           4.6          3.1           1.5          0.2   setosa

In [15]:
for _ in range(5):
    print("mm\n")

mm

mm

mm

mm

mm



In [16]:
for _ in xrange(5):
    print("mm\n")

NameError: name 'xrange' is not defined

In [22]:
for x in range(4):
    print ('x=%d'  (x))

TypeError: 'str' object is not callable

In [23]:
X = np.arange(9.0)

NameError: name 'np' is not defined

In [24]:
import numpy as np

In [25]:
X = np.arange(9.0)

In [26]:
X

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [27]:
Y = np.random.rand(1, 9)

In [28]:
Y

array([[ 0.6664415 ,  0.64920979,  0.31857624,  0.82981384,  0.73932867,
         0.35751178,  0.72668932,  0.81121595,  0.65778427]])

In [29]:
Z = np.multiply(X, Y)

In [30]:
Z

array([[ 0.        ,  0.64920979,  0.63715249,  2.48944152,  2.95731468,
         1.78755892,  4.36013593,  5.67851167,  5.26227418]])

In [31]:
Z = 0.1 * Z

In [32]:
Z

array([[ 0.        ,  0.06492098,  0.06371525,  0.24894415,  0.29573147,
         0.17875589,  0.43601359,  0.56785117,  0.52622742]])

In [33]:
X = np.random.rand(2, 3)

In [34]:
X

array([[ 0.3864198 ,  0.27461248,  0.10103611],
       [ 0.17781428,  0.95391715,  0.05789641]])

In [35]:
new_column = np.ones(2)

In [36]:
new_column

array([ 1.,  1.])

In [37]:
new_column = new_column.reshape(2, 1)

In [38]:
new_column

array([[ 1.],
       [ 1.]])

In [39]:
new_column = new_column.reshape(2, )

In [40]:
new_column

array([ 1.,  1.])

In [41]:
new_column.shape

(2,)

In [42]:
new_column.reshape(2, 1)

array([[ 1.],
       [ 1.]])

In [43]:
new_column.shape

(2,)

In [44]:
X = np.append(new_column, X, 1)

IndexError: axis 1 out of bounds [0, 1)

In [45]:
X = np.append(new_column, X, 0)

ValueError: all the input arrays must have same number of dimensions

In [46]:
X.shape

(2, 3)

In [47]:
new_column.shape

(2,)

In [48]:
new_column2 = X.sum(1)[..., None]

In [49]:
new_column2.shape

(2, 1)

In [50]:
new_column2

array([[ 0.76206839],
       [ 1.18962784]])

In [51]:
new_column

array([ 1.,  1.])

In [52]:
new_column.reshape(2, 1)

array([[ 1.],
       [ 1.]])

In [53]:
new_column = new_column.reshape(2, 1)

In [54]:
X

array([[ 0.3864198 ,  0.27461248,  0.10103611],
       [ 0.17781428,  0.95391715,  0.05789641]])

In [55]:
X_append = np.append(new_column, X, 1)

In [56]:
X_append

array([[ 1.        ,  0.3864198 ,  0.27461248,  0.10103611],
       [ 1.        ,  0.17781428,  0.95391715,  0.05789641]])

In [57]:
X_append.shape

(2, 4)